# Generated by Django 3.2.6 on 2021-08-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_linea', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('precio_unitario', models.FloatField()),
                ('monto_total', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('codigo_impuesto', models.IntegerField()),
                ('codigo_tarifa', models.IntegerField()),
                ('tarifa', models.IntegerField()),
                ('monto', models.FloatField()),
                ('impuesto_neto', models.FloatField()),
                ('monto_total_linea', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=200)),
                ('num_identificacion', models.IntegerField()),
                ('tipo_identificacion', models.IntegerField()),
                ('nombre_comercial', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=500)),
                ('provincia', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
                ('otras_senas', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=200)),
                ('num_identificacion', models.IntegerField()),
                ('tipo_identificacion', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=500)),
                ('provincia', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
                ('otras_senas', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_serv_gravados', models.FloatField()),
                ('total_serv_exentos', models.FloatField()),
                ('total_serv_exonerados', models.FloatField()),
                ('total_mercancias_gravadas', models.FloatField()),
                ('total_mercancias_exentas', models.FloatField()),
                ('total_mercancias_exoneradas', models.FloatField()),
                ('total_gravado', models.FloatField()),
                ('total_exento', models.FloatField()),
                ('total_exonerado', models.FloatField()),
                ('total_venta', models.FloatField()),
                ('total_descuentos', models.FloatField()),
                ('total_venta_neta', models.FloatField()),
                ('total_impuestos', models.FloatField()),
                ('total_comprobante', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=200)),
                ('codigo_actividad', models.IntegerField()),
                ('numero_consecutivo', models.IntegerField()),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('condicion_venta', models.IntegerField()),
                ('medio_pago', models.IntegerField()),
                ('plazo_credito', models.IntegerField()),
                ('detalle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.detalle')),
                ('emisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.emisor')),
                ('receptor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.receptor')),
                ('resumen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.resumen')),
            ],
        ),
    ]
