# Generated by Django 3.2.6 on 2021-08-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_linea', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('precio_unitario', models.FloatField()),
                ('monto_total', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('codigo_impuesto', models.IntegerField()),
                ('codigo_tarifa', models.IntegerField()),
                ('tarifa', models.IntegerField()),
                ('monto', models.FloatField()),
                ('impuesto_neto', models.FloatField()),
                ('monto_total_linea', models.FloatField()),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('identificacion', models.CharField(max_length=200, verbose_name='Identificación')),
                ('num_identificacion', models.IntegerField(verbose_name='Numero de Identificación')),
                ('tipo_identificacion', models.IntegerField(verbose_name='Tipo de Identificación')),
                ('nombre_comercial', models.CharField(max_length=500, verbose_name='Nombre Comercial')),
                ('ubicacion', models.CharField(max_length=500, verbose_name='Ubicación')),
                ('provincia', models.CharField(max_length=200, verbose_name='Provincia')),
                ('canton', models.CharField(max_length=200, verbose_name='Cantón')),
                ('distrito', models.CharField(max_length=200, verbose_name='Distrito')),
                ('otras_senas', models.CharField(max_length=400, verbose_name='Otras señas')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.CharField(max_length=200, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Emisor',
                'verbose_name_plural': 'Emisores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('identificacion', models.CharField(max_length=200, verbose_name='Identificación')),
                ('num_identificacion', models.IntegerField(verbose_name='Numero de Identificación')),
                ('tipo_identificacion', models.IntegerField(verbose_name='Tipo de Identificación')),
                ('nombre_comercial', models.CharField(max_length=500, verbose_name='Nombre Comercial')),
                ('ubicacion', models.CharField(max_length=500, verbose_name='Ubicación')),
                ('provincia', models.CharField(max_length=200, verbose_name='Provincia')),
                ('canton', models.CharField(max_length=200, verbose_name='Cantón')),
                ('distrito', models.CharField(max_length=200, verbose_name='Distrito')),
                ('otras_senas', models.CharField(max_length=400, verbose_name='Otras señas')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.CharField(max_length=200, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_serv_gravados', models.FloatField()),
                ('total_serv_exentos', models.FloatField()),
                ('total_serv_exonerados', models.FloatField()),
                ('total_mercancias_gravadas', models.FloatField()),
                ('total_mercancias_exentas', models.FloatField()),
                ('total_mercancias_exoneradas', models.FloatField()),
                ('total_gravado', models.FloatField()),
                ('total_exento', models.FloatField()),
                ('total_exonerado', models.FloatField()),
                ('total_venta', models.FloatField()),
                ('total_descuentos', models.FloatField()),
                ('total_venta_neta', models.FloatField()),
                ('total_impuestos', models.FloatField()),
                ('total_comprobante', models.FloatField()),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resumenes',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=200, verbose_name='Clave')),
                ('codigo_actividad', models.IntegerField(verbose_name='Código de actividad')),
                ('numero_consecutivo', models.IntegerField(verbose_name='Número de consecutivo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('condicion_venta', models.IntegerField(verbose_name='Condición de venta')),
                ('medio_pago', models.IntegerField(verbose_name='Medio de pago')),
                ('plazo_credito', models.IntegerField(verbose_name='Plazo de crédito')),
                ('detalle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.detalle')),
                ('emisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.emisor')),
                ('receptor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.receptor')),
                ('resumen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.resumen')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
