# Generated by Django 3.2.6 on 2021-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
